### PR TITLE
Made the fix

### PR DESCRIPTION
**Pull request by achenPDFTron**

### CODE REVIEW

File: server/serve.js [hunk 1]
```diff
@@ -21,11 +21,11 @@ app.get('/server/demo.pdf', (req, res) => {
 });
 
 // Run server
-app.listen(3000, 'localhost', (err) => {
+app.listen(3005, 'localhost', (err) => {
```
Comment (achenPDFTron) [inline server/serve.js]: changed port number just for testing convenience.

File: client/index.js [hunk 2]
```diff
@@ -1,5 +1,5 @@
 var viewerElement = document.getElementById('viewer');
-var viewer = new PDFTron.WebViewer({
+var viewer = WebViewer({
```
Comment (achenPDFTron) [inline client/index.js]: addressed this error:
TypeError: (new PDFTron.WebViewer(...)).then is not a function

**Comment by achenPDFTron** [comment]
@ZhijieZhang i have made fixes for this sample to work with webviewer 6.0

**Review by mparizeau-pdftron — APPROVED** [review]
